//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCrudTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALPlant2
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public string Model_Name { get; set; }
        public string Serial_Number { get; set; }
        public string Calibrated { get; set; }
        public string Due_Date { get; set; }
        public string RO { get; set; }
        public string E_ID { get; set; }
        public string SENT_OUT { get; set; }
        public string Found { get; set; }
        public string Remarks { get; set; }
        public string Cal_Location { get; set; }
        public string User_Name { get; set; }
        public string Owner_Name { get; set; }
        public string Cal_BACK_Date { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Notes { get; set; }
        public string ImageFileName { get; set; }
        public string Location { get; set; }
        public Nullable<bool> Discarded { get; set; }
        public Nullable<bool> NotInUse { get; set; }
        public string FileName1 { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
