//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFCrudTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Program
    {
        public int ID { get; set; }
        public string Class_ID { get; set; }
        public string ClassTitle { get; set; }
        public Nullable<System.DateTime> ClassDate { get; set; }
        public Nullable<decimal> Course_Duration_hrs_ { get; set; }
        public string Distribution { get; set; }
        public string Supervisor1 { get; set; }
        public string Supervisor2 { get; set; }
        public string Supervisor3 { get; set; }
        public string Instructors { get; set; }
        public string Site_Location { get; set; }
        public string Class_Description { get; set; }
        public string File_Name1 { get; set; }
        public string File_Name2 { get; set; }
        public string File_Name3 { get; set; }
        public string Instructor_Name { get; set; }
        public string Instructor_Title { get; set; }
        public string Instructor_Company { get; set; }
        public string Instructor_Address { get; set; }
        public string Note { get; set; }
    }
}
